<!DOCTYPE html>
<html>
    <head>
        <title>Pagina web de ejemplo

        </title>
    </head>
    <body>
        <h1>Este es un ejemplo que porgram en html

        </h1>
        
    </body>
</html>
